<a href="https://colab.research.google.com/github/memeanji/pandas_studylog/blob/master/day02_pandasipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 판다스 기초문법

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
tt = sns.load_dataset('titanic')

In [ ]:
##df
type(tt[['survived','pclass']])

pandas.core.frame.DataFrame

In [ ]:
#시리즈 형태
type(tt['survived'])

pandas.core.series.Series

In [ ]:
#연산을 빠르게 하기 위한 형태
sum(tt['fare'])

28693.949299999967

In [ ]:
#데이터프레임은 빠른 연산이 어려움
sum(tt[['fare']])

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
sum(tt[['fare','survived']])

TypeError: unsupported operand type(s) for +: 'int' and 'str'

### 판다스 기초 문법
- head(),tail() , 데이터를 요약해서 보기
- shape , 행/열 추출
- info() ,데이터의 전반적인 정보 확인
- describe() , 데이터의 요약통계치 확인
- dtypes , 데이터 타입 확인
- columns , 데이터 컬럼만 추출

In [ ]:
#앞 데이터 5개 정도 추출
tt.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
tt.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
##행열
tt.shape

(891, 15)

In [ ]:
## 데이터의 정보를 한번에 볼 수 있는 info
tt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
### 요약통계치
# 연속적인 숫자는 기초통계 평균, 분산이 가능함
# 등수 빈도값, 유니크한 값, 다중값
tt. describe() # 수치형 값만 나옴

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
tt.describe(include='all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
tt.describe(include=["number"])

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
tt.describe(include=['category','object'])

         sex embarked  class  who deck  embark_town alive
count    891      889    891  891  203          889   891
unique     2        3      3    3    7            3     2
top     male        S  Third  man    C  Southampton    no
freq     577      644    491  537   59          644   549

In [ ]:
list(tt.columns)

['survived',
 'pclass',
 'sex',
 'age',
 'sibsp',
 'parch',
 'fare',
 'embarked',
 'class',
 'who',
 'adult_male',
 'deck',
 'embark_town',
 'alive',
 'alone']

### 상황에 따른 간단한 데이터 프레임 조작 방법
1. 컬럼 변경
- 데이터프레임 컬럼명을 변경해야 하는 경우
- 어떤 식으로 변경해야 하는지?

In [ ]:
df = pd. DataFrame({'분반':['파문기','SQL','모델링','데이터분석'],
                    '인ㅇㅓㄴ':[100,200,300,400]})

In [ ]:
df

      분반  인ㅇㅓㄴ
0    파문기   100
1    SQL   200
2    모델링   300
3  데이터분석   400

In [ ]:
##변수명을 바꿀 때 rename()
#데이터프레임 .rename(columns = {'기존컬럼':"변경컬럼"})
df.rename(columns = {'인ㅇㅓㄴ':'인원'})

      분반   인원
0    파문기  100
1    SQL  200
2    모델링  300
3  데이터분석  400

In [ ]:
df

      분반  인ㅇㅓㄴ
0    파문기   100
1    SQL   200
2    모델링   300
3  데이터분석   400

- 데이터프레임은 원본데이터를 보존하려는 성질이 있따보니 바로 바뀌지 않음
- 원본 데이터를 바꾸려면 3가지를 생각해야 함
    1. 원본데이터 변수명에 그대로 원본데이터를 넣으면 됨. 변수 사용해서 변수교체
    2. 바로 문법에서 inplace=True 대치를 바로 진행하는 경우
    3. copy() 원본데이터를 카피하여서 실제 원본데이터는 그대로 두고, 내가 분석할 데이터만 변경하여 사용
    
    
    why?
    1. 어느 순간 데이터를 분석하다보면 뭐가 원본이고 무엇을 하고 있는지 가끔 혼선이 올 경우
    2. A로 전처리했는데 B로 전처리해 함. 근데 원본이 없다? 충격과 공포
    3. 이런 여러 예외 케이스를 대응하기 위해 원본데이터는 그대로 두는게 처음부터 좋음

In [ ]:
df_1 = df.copy()
df_2 = df.copy()

In [ ]:
#변수 교체
df_1=df_1.rename(columns={'인ㅇㅓㄴ':'인원'})

In [ ]:
#이 문법을 사용하면서 바로 원본을 수정하겠다 선언하는게 inplace True
df_2.rename(columns={'인ㅇㅓㄴ':'인원'},inplace=True)

###파생변수 만들기
- 기존의 변수를 이용해서 새로운 변수를 만드는 것
- 기존의 변수의 영향을 받기 때문에 정말 꼭 만들어야 하는 지 고민해보기
- ML 등의 feature로 사용할 떄 기존 변수와의 관계도 꼭 고려해보기
- 무조건 파생변수를 많이 만드는 건 차원이 더 추가되는 것과 같아서 조심해야함

In [ ]:
bda_class=pd.DataFrame({
    '이름':['김민지','이조아','김정윤','김찬규','이또아'],
    '상점':[10,20,30,40,50],
    '벌점':[1,2,3,4,5]
    })

In [ ]:
bda_class

    이름  상점  벌점
0  김민지  10   1
1  이조아  20   2
2  김정윤  30   3
3  김찬규  40   4
4  이또아  50   5

In [ ]:
# 상점 - 벌점 = 최종상태 컬럼
# 최종상태 변수에 값을 넣으려고 함

In [ ]:
#변수처럼 사용할 수 있음
bda_class['최종상태'] = bda_class['상점'] - bda_class['벌점']

In [ ]:
#최종상태에서 추가로 20점 이상이면 pass, 이하면 fail 새로운 또 파생변수를 만들었음
bda_class

    이름  상점  벌점  최종상태
0  김민지  10   1     9
1  이조아  20   2    18
2  김정윤  30   3    27
3  김찬규  40   4    36
4  이또아  50   5    45

In [ ]:
### numpy를 사용해서 파생변수를 만듦
### 인덱스로 접근
### 넘파이를 사용해서 특정 기준에 인덱스를 추출하여서 해당 인덱스에 값을 매핑하는 형태로 감
np.where(bda_class['최종상태']>=20) #인덱스를 반환

(array([2, 3, 4]),)

In [ ]:
bda_class['수료여부']=np.where(bda_class['최종상태']>=20,'pass','fail')

In [ ]:
#파생변수도 쉽게 만들 수 있음
bda_class['new'] = 1,2,3,4,5

In [ ]:
bda_class

    이름  상점  벌점  최종상태  수료여부  new
0  김민지  10   1     9  fail    1
1  이조아  20   2    18  fail    2
2  김정윤  30   3    27  pass    3
3  김찬규  40   4    36  pass    4
4  이또아  50   5    45  pass    5

In [ ]:
## 수료여부 자료들은 문자값 빈도를 바로 카운팅하고 싶음
## value_counts()

bda_class['수료여부'].value_counts()

수료여부
pass    3
fail    2
Name: count, dtype: int64

In [ ]:
tt['embark_town'].value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

### 데이터 찾아주는 문법
- loc : Location, 인덱스 -> 처음 생성된 데이터프레임의 인덱스
- iloc : integer Location, 넘버링된 인덱스 -> 현재 기준의 데이터프레임의 순서

#인덱스
-사용법
    - loc[인덱스]
    - iloc [인덱스]
- 행과 열을 찍는 방법
    - loc : 모두 다 명시적으로 정확하게 적어야 함
    - iloc : 모두 다 int로 적어야 함

In [ ]:
bda_class

    이름  상점  벌점  최종상태  수료여부  new
0  김민지  10   1     9  fail    1
1  이조아  20   2    18  fail    2
2  김정윤  30   3    27  pass    3
3  김찬규  40   4    36  pass    4
4  이또아  50   5    45  pass    5

- 시리즈 형태에서 인덱스 찾기

In [ ]:
bda_class['이름'].loc[0]

'김민지'

In [ ]:
bda_class['이름'].iloc[0]

'김민지'

In [ ]:
tt_1=tt['fare'].tail()

In [ ]:
# loc, iloc의 차이
print('loc',tt_1.loc[887])

loc 30.0

In [ ]:
print('iloc',tt_1.iloc[1])

iloc 30.0

In [ ]:
tt_1

886    13.00
887    30.00
888    23.45
889    30.00
890     7.75
Name: fare, dtype: float64

- loc 와 iloc 행과 열을 모두 추출해보기
- range(::) 개념과 동일함
### loc[행:열]
- 행과 열 기준으로 값을 적어야 함
- 기준을 나누기 위해서는 , 콤마 !

In [ ]:
tt.loc[5:80:3,['fare','survived']]

       fare  survived
5    8.4583         0
8   11.1333         1
11  26.5500         1
14   7.8542         0
17  13.0000         1
20  26.0000         0
23  35.5000         1
26   7.2250         0
29   7.8958         0
32   7.7500         1
35  52.0000         0
38  18.0000         0
41  21.0000         0
44   7.8792         1
47   7.7500         1
50  39.6875         0
53  26.0000         1
56  10.5000         1
59  46.9000         0
62  83.4750         0
65  15.2458         1
68   7.9250         1
71  46.9000         0
74  56.4958         1
77   8.0500         0
80   9.0000         0

In [ ]:
tt.iloc[5:80:3,1:5]

    pclass     sex   age  sibsp
5        3    male   NaN      0
8        3  female  27.0      0
11       1  female  58.0      0
14       3  female  14.0      0
17       2    male   NaN      0
20       2    male  35.0      0
23       1    male  28.0      0
26       3    male   NaN      0
29       3    male   NaN      0
32       3  female   NaN      0
35       1    male  42.0      1
38       3  female  18.0      2
41       2  female  27.0      1
44       3  female  19.0      0
47       3  female   NaN      0
50       3    male   7.0      4
53       2  female  29.0      1
56       2  female  21.0      0
59       3    male  11.0      5
62       1    male  45.0      1
65       3    male   NaN      1
68       3  female  17.0      4
71       3  female  16.0      5
74       3    male  32.0      0
77       3    male   NaN      0

## 데이터 전처리, 추출 등에 필요한 기초 문법
- 행과 열의 기준 외 특정 데이터 추출 조건에 따른 데이터 추출 작업
- loc, iloc 행과 열 좌표 위치
- 성별이 여자인 경우 또는 성별이 남자인 경우

    - query() , 데이터 추출
    - df.loc/iloc[불림참값] , 데이터 추출
    - df[] , 열 기준 추출
    - sort_values(), 정렬
    - group by() , 그룹바이
    - assgin() , 변수 추가할 때 사용하는 함수
    - merge() , 병합
    - concat() , 병합
    - apply() , 전처리 전체 적용

In [ ]:
#성별이 남성인 경우
#query (특정 요구조건을 적으면 됨)
## 문자열 데이터는 같은지 여부로 데이터 추출 가능

tt.query("sex =='male'")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
## 수치형 데이터는 ?
## 대소비교 < > <= >=
tt.query('fare>50')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False

In [ ]:
## 다중 조건인 경우는?
## 요금은 50 이상에 나이는 20 이상 다중조건
## and , or 조건 값이 달라짐
tt.query('fare>50 & age<20')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
27,0,1,male,19.00,3,2,263.0000,S,First,man,True,C,Southampton,no,False
291,1,1,female,19.00,1,0,91.0792,C,First,woman,False,B,Cherbourg,yes,False
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
307,1,1,female,17.00,1,0,108.9000,C,First,woman,False,C,Cherbourg,yes,False
311,1,1,female,18.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
329,1,1,female,16.00,0,1,57.9792,C,First,woman,False,B,Cherbourg,yes,False
385,0,2,male,18.00,0,0,73.5000,S,Second,man,True,NaN,Southampton,no,True
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
445,1,1,male,4.00,0,2,81.8583,S,First,child,False,A,Southampton,yes,False
504,1,1,female,16.00,0,0,86.5000,S,First,woman,False,B,Southampton,yes,True
505,0,1,male,18.00,1,0,108.9000,C,First,man,True,C,Cherbourg,no,False
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
585,1,1,female,18.00,0,2,79.6500,S,First,woman,False,E,Southampton,yes,False
689,1,1,female,15.00,0,1,211.3375,S,First,child,False,B,Southampton,yes,False
700,1,1,female,18.00,1,0,227.5250,C,First,woman,False,C,Cherbourg,yes,False
748,0,1,male,19.00,1,0,53.1000,S,First,man,True,D,Southampton,no,False
781,1,1,female,17.00,1,0,57.0000,S,First,woman,False,B,Southampton,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False

In [ ]:
# and 조건 , or 조건
tt.query('fare>50 | age<20')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [ ]:
tt.query("embark_town in ['Cherbourg','Southampton']")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

- df[[불린참값]] - 데이터 추출
    - 정말 많이 사용하는 문법

### 불린참값
- df[불린참값]는 True인 행만 골라주는 기능이야!

- 이 불린값은 주로 df['컬럼명'] > 값, ==, != 같은 조건식으로 만들어.
->  데이터 추출, 필터링, 조건부 분석에서 자주 씀

In [ ]:
tt[tt['sex'] == 'female']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [ ]:
# 데이터프레임은 재구조화가 된다라는 거임

tt[(tt['sex']=='female')&(tt['fare']>50)][['survived','fare']]

     survived      fare
1           1   71.2833
3           1   53.1000
31          1  146.5208
52          1   76.7292
61          1   80.0000
..        ...       ...
849         1   89.1042
856         1  164.8667
863         0   69.5500
871         1   52.5542
879         1   83.1583

[87 rows x 2 columns]